name: Create Release

on:
  workflow_dispatch:  # Enables manual trigger
  push:
    branches:
      - main        # Run on push to main branch
    tags:
      - 'v*'       # Run on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install required tools (imagemagick for icons)
      - name: Install dependencies
        run: sudo apt-get install -y imagemagick
      
      # Generate icons
      - name: Generate icons
        run: |
          convert -size 128x128 xc:'#46178F' -fill white -font Arial-Bold -pointsize 80 -gravity center -draw "text 0,0 'K'" icon128.png
          convert icon128.png -resize 48x48 icon48.png
          convert icon128.png -resize 16x16 icon16.png
      
      # Create ZIP file
      - name: Create ZIP
        run: |
          zip -r kahoot-viewer.zip manifest.json background.js content.js options.html options.js icon16.png icon48.png icon128.png README.md
      
      # Create Release and Upload Asset (only on tag push)
      - name: Release and Upload Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: kahoot-viewer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Upload artifact (always)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: kahoot-viewer.zip
