name: Create Release

on:
  workflow_dispatch:  # Enables manual trigger
  push:
    branches:
      - main        # Run on push to main branch
    tags:
      - 'v*'       # Run on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Install required tools (imagemagick for icons)
      - name: Install dependencies
        run: sudo apt-get install -y imagemagick
      
      # Generate icons
      - name: Generate icons
        run: |
          convert -size 128x128 xc:'#46178F' -fill white -font Arial-Bold -pointsize 80 -gravity center -draw "text 0,0 'K'" icon128.png
          convert icon128.png -resize 48x48 icon48.png
          convert icon128.png -resize 16x16 icon16.png
      
      # Create ZIP file
      - name: Create ZIP
        run: |
          zip -r kahoot-viewer.zip manifest.json background.js content.js options.html options.js icon16.png icon48.png icon128.png README.md
      
      # Create GitHub Release (only on tag push)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      
      # Upload ZIP file to release (only on tag push)
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kahoot-viewer.zip
          asset_name: kahoot-viewer.zip
          asset_content_type: application/zip
      
      # Upload artifact (always)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension-package
          path: kahoot-viewer.zip
